included:
  - VoiceAssistApp
  - Tests
excluded:
  - Pods
  - .build

opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - closure_spacing
  - overridden_super_call
  - redundant_nil_coalescing
  - private_outlet
  - nimble_operator
  - attributes
  - operator_usage_whitespace
  - closure_end_indentation
  - first_where
  - prohibited_super_call
  - fatal_error_message
  - vertical_parameter_alignment_on_call
  - let_var_whitespace
  - unneeded_parentheses_in_closure_argument
  - pattern_matching_keywords
  - array_init
  - literal_expression_end_indentation

line_length:
  warning: 120
  error: 200
  
function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

large_tuple:
  warning: 3
  error: 4

identifier_name:
  min_length:
    warning: 2
  excluded:
    - id
    - x
    - y
    - dx
    - dy

type_name:
  min_length:
    warning: 3
  max_length:
    warning: 50
    error: 60

cyclomatic_complexity:
  warning: 15
  error: 25

reporter: "xcode"
