name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - '**.swift'
      - '**.md'
      - 'Documentation.docc/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
          
      - name: Build Documentation
        run: |
          xcodebuild docbuild \
            -scheme VoiceAssistApp \
            -destination 'platform=macOS' \
            -derivedDataPath ./derived_data
            
      - name: Process Documentation
        run: |
          cp -r ./derived_data/Build/Products/Debug/VoiceAssist.doccarchive ./docs
          
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './docs'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

  generate-changelog:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Generate Documentation Changelog
        run: |
          echo "# Documentation Changes" > docs_changelog.md
          echo "## Latest Changes" >> docs_changelog.md
          git log -p --no-merges Documentation.docc/ | grep -E "^\+.*" >> docs_changelog.md
          
      - name: Create Issue on Documentation Update
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Documentation Updates Available
          content-filepath: ./docs_changelog.md
          labels: documentation
          assignees: tmm22
